title: 이것 저것
description: 이것 저것 적는 블로그입니다.
theme: just-the-docs

url: https://cutepassions.github.io

color_scheme: dark

aux_links:
  Github: https://github.com/cutepassions
  Tech Blog (Velog): https://velog.io/@cutepassions
