title: 이것 저것
description: 이것 저것 적는 블로그입니다.
theme: just-the-docs

search:
  enabled: true
  placeholder: "검색어를 입력하세요."
  tokinizer_separator: /[\s/]+/

# color_scheme: dark
permalink: pretty

url: https://cutepassions.github.io

footer_content: ""

aux_links:
  Github: https://github.com/cutepassions
  Tech Blog (Velog): https://velog.io/@cutepassions
