title: 이것 저것
description: 이것 저것 적는 블로그입니다.
theme: just-the-docs

search_enabled: true
search.tokenizer_separator: /[\s/]+/

# color_scheme: dark
google_analytics: G-VVX12S13VM
permalink: pretty

url: https://cutepassions.github.io

footer_content: ""

aux_links:
  Github: https://github.com/cutepassions
  Tech Blog (Velog): https://velog.io/@cutepassions
